# This my first nginx Dockerfile
# Version 1.0

# 基础镜像
FROM ubuntu:20.04

# 工作目录
WORKDIR /root

# 运行命令
RUN apt-get update && apt-get install -y wget && wget https://downloads.apache.org/tomcat/tomcat-9/v9.0.38/bin/apache-tomcat-9.0.38.tar.gz && tar -xvzf apache-tomcat-9.0.38.tar.gz


