# Version: 0.0.1
FROM centos
MAINTAINER que1 "que1@sina.com"
RUN yum install -y wget
RUN yum install -y tar
RUN wget https://mirrors.cnnic.cn/apache/tomcat/tomcat-9/v9.0.10/bin/apache-tomcat-9.0.10.tar.gz 
RUN tar -xvzf apache-tomcat-9.0.10.tar.gz
EXPOSE 8080
